# Generated by Django 3.1.5 on 2021-01-26 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name1')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password1', models.CharField(max_length=200)),
                ('email1', models.EmailField(max_length=200, unique=True)),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name1')),
            ],
        ),
        migrations.CreateModel(
            name='learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude1', models.FloatField()),
                ('longitude1', models.FloatField()),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name1')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tagged')),
            ],
        ),
        migrations.CreateModel(
            name='iddistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=10, unique=True)),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name1')),
            ],
        ),
        migrations.CreateModel(
            name='hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby1', models.IntegerField()),
                ('hobby2', models.IntegerField()),
                ('hobby3', models.IntegerField()),
                ('hobby4', models.IntegerField()),
                ('hobby5', models.IntegerField()),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name1')),
            ],
        ),
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.CharField(max_length=1000)),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name1')),
            ],
        ),
        migrations.CreateModel(
            name='birth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name1')),
            ],
        ),
    ]
