# Generated by Django 3.1.4 on 2021-01-16 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude1', models.FloatField()),
                ('longitude1', models.FloatField()),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
            ],
        ),
        migrations.CreateModel(
            name='hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=200)),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name')),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='name1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name'),
        ),
    ]
