# Generated by Django 3.1.4 on 2021-01-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210116_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='name',
            new_name='Name1',
        ),
    ]
