# Generated by Django 3.1.4 on 2021-01-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210116_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='iddistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=10, unique=True)),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name1')),
            ],
        ),
    ]
