# Generated by Django 3.1.4 on 2021-01-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
