# Generated by Django 3.1.4 on 2021-01-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210117_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbies',
            name='hobby',
        ),
        migrations.AddField(
            model_name='hobbies',
            name='hobby1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='hobby2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='hobby3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='hobby4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='hobby5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.CharField(max_length=1000)),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name1')),
            ],
        ),
    ]
