# Generated by Django 3.1.4 on 2021-01-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210118_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby1', models.IntegerField()),
                ('hobby2', models.IntegerField()),
                ('hobby3', models.IntegerField()),
                ('hobby4', models.IntegerField()),
                ('hobby5', models.IntegerField()),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name1')),
            ],
        ),
        migrations.DeleteModel(
            name='hobbies',
        ),
    ]
