# Generated by Django 3.1.4 on 2021-01-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.IntegerField()),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.name1')),
            ],
        ),
        migrations.AlterField(
            model_name='learn',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tagged'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
