# Generated by Django 3.1.4 on 2021-01-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210118_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagged',
            name='name1',
        ),
    ]
